/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivateImport } from './routes/_private'
import { Route as AuthImport } from './routes/_auth'
import { Route as PrivateIndexImport } from './routes/_private/index'
import { Route as PrivateAccountImport } from './routes/_private/account'
import { Route as PrivateAdminImport } from './routes/_private/_admin'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthSigninImport } from './routes/_auth/signin'
import { Route as AuthResetPasswordImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordImport } from './routes/_auth/forgot-password'
import { Route as PrivateAdminModerationImport } from './routes/_private/_admin/moderation'

// Create/Update Routes

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const PrivateIndexRoute = PrivateIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateAccountRoute = PrivateAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateAdminRoute = PrivateAdminImport.update({
  id: '/_admin',
  getParentRoute: () => PrivateRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)

const PrivateAdminModerationRoute = PrivateAdminModerationImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => PrivateAdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_private/_admin': {
      id: '/_private/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateAdminImport
      parentRoute: typeof PrivateImport
    }
    '/_private/account': {
      id: '/_private/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof PrivateAccountImport
      parentRoute: typeof PrivateImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/_admin/moderation': {
      id: '/_private/_admin/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof PrivateAdminModerationImport
      parentRoute: typeof PrivateAdminImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PrivateAdminRouteChildren {
  PrivateAdminModerationRoute: typeof PrivateAdminModerationRoute
}

const PrivateAdminRouteChildren: PrivateAdminRouteChildren = {
  PrivateAdminModerationRoute: PrivateAdminModerationRoute,
}

const PrivateAdminRouteWithChildren = PrivateAdminRoute._addFileChildren(
  PrivateAdminRouteChildren,
)

interface PrivateRouteChildren {
  PrivateAdminRoute: typeof PrivateAdminRouteWithChildren
  PrivateAccountRoute: typeof PrivateAccountRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateAdminRoute: PrivateAdminRouteWithChildren,
  PrivateAccountRoute: PrivateAccountRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PrivateAdminRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/account': typeof PrivateAccountRoute
  '/': typeof PrivateIndexRoute
  '/moderation': typeof PrivateAdminModerationRoute
}

export interface FileRoutesByTo {
  '': typeof PrivateAdminRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/account': typeof PrivateAccountRoute
  '/': typeof PrivateIndexRoute
  '/moderation': typeof PrivateAdminModerationRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_private': typeof PrivateRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_private/_admin': typeof PrivateAdminRouteWithChildren
  '/_private/account': typeof PrivateAccountRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/_admin/moderation': typeof PrivateAdminModerationRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/account'
    | '/'
    | '/moderation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/account'
    | '/'
    | '/moderation'
  id:
    | '__root__'
    | '/_auth'
    | '/_private'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_private/_admin'
    | '/_private/account'
    | '/_private/'
    | '/_private/_admin/moderation'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PrivateRoute: typeof PrivateRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_private"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/forgot-password",
        "/_auth/reset-password",
        "/_auth/signin",
        "/_auth/signup"
      ]
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/_admin",
        "/_private/account",
        "/_private/"
      ]
    },
    "/_auth/forgot-password": {
      "filePath": "_auth/forgot-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/reset-password": {
      "filePath": "_auth/reset-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/signin": {
      "filePath": "_auth/signin.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx",
      "parent": "/_auth"
    },
    "/_private/_admin": {
      "filePath": "_private/_admin.tsx",
      "parent": "/_private",
      "children": [
        "/_private/_admin/moderation"
      ]
    },
    "/_private/account": {
      "filePath": "_private/account.tsx",
      "parent": "/_private"
    },
    "/_private/": {
      "filePath": "_private/index.tsx",
      "parent": "/_private"
    },
    "/_private/_admin/moderation": {
      "filePath": "_private/_admin/moderation.tsx",
      "parent": "/_private/_admin"
    }
  }
}
ROUTE_MANIFEST_END */
